[2024-04-16T04:31:30.268+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: first_dag.parse_apod_data scheduled__2024-02-20T00:00:00+00:00 [queued]>
[2024-04-16T04:31:30.277+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: first_dag.parse_apod_data scheduled__2024-02-20T00:00:00+00:00 [queued]>
[2024-04-16T04:31:30.278+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-04-16T04:31:30.278+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2024-04-16T04:31:30.278+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-04-16T04:31:30.292+0000] {taskinstance.py:1383} INFO - Executing <Task(_PythonDecoratedOperator): parse_apod_data> on 2024-02-20 00:00:00+00:00
[2024-04-16T04:31:30.296+0000] {standard_task_runner.py:55} INFO - Started process 1246 to run task
[2024-04-16T04:31:30.298+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'parse_apod_data', 'scheduled__2024-02-20T00:00:00+00:00', '--job-id', '1219', '--raw', '--subdir', 'DAGS_FOLDER/FirstDag.py', '--cfg-path', '/tmp/tmpwpf2cyi0']
[2024-04-16T04:31:30.299+0000] {standard_task_runner.py:83} INFO - Job 1219: Subtask parse_apod_data
[2024-04-16T04:31:30.360+0000] {task_command.py:376} INFO - Running <TaskInstance: first_dag.parse_apod_data scheduled__2024-02-20T00:00:00+00:00 [running]> on host b0ce51d36eb8
[2024-04-16T04:31:30.428+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=first_dag
AIRFLOW_CTX_TASK_ID=parse_apod_data
AIRFLOW_CTX_EXECUTION_DATE=2024-02-20T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-02-20T00:00:00+00:00
[2024-04-16T04:31:30.429+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 188, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/FirstDag.py", line 32, in parse_apod_data
    title=row.get('title'),
AttributeError: 'str' object has no attribute 'get'
[2024-04-16T04:31:30.437+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=first_dag, task_id=parse_apod_data, execution_date=20240220T000000, start_date=20240416T043130, end_date=20240416T043130
[2024-04-16T04:31:30.447+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1219 for task parse_apod_data ('str' object has no attribute 'get'; 1246)
[2024-04-16T04:31:30.470+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2024-04-16T04:31:30.499+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
